USE ABC71DB
SELECT  GRUPO
	,	C_PROD AS 'CÓDIGO'
	,	DESCRICAO AS 'DESCRIÇÃO'
	,	UNIDADE
	,	SALDO AS 'SALDO FISICO'
	,	'' AS ESTOQUE
FROM VW_ESTQ WHERE SUB_DIVISAO_2 = 'UNIFORMES / E.P.I.' AND EMP_FIL = 2310001 AND GRUPO LIKE '70303%' AND DEPOSITO = 20
ORDER BY DESCRICAO
